### ISSUE TITLE
Release on npm?

### ISSUE THREAD

**Issue by francois2metz** [lmatteis/node-trello#7]
Hi,

Can you publish it on npm? It would be also nice to rename the package from _node-trello_ to _trello_.

**Comment by lmatteis** [comment]
Always wanted to add it to npm but never had time, so I just did it.
You can now `npm install node-trello`.
I'm keeping the _node-trello_ name as _trello_ itself is too generic. Thanks!

**Comment by francois2metz** [comment]
Thanks!
